import { SmartBuffer } from './SmartBuffer';
export declare class DynamicSmartBuffer {
    private _offset;
    private _size;
    private _buffer;
    constructor(_bytes?: Uint8Array);
    seek(newOffset: number): void;
    compact(): void;
    get size(): number;
    get offset(): number;
    static ofBinaryString(str: string): DynamicSmartBuffer;
    static ofBase64String(str: string): DynamicSmartBuffer;
    static ofHexString(str: string): DynamicSmartBuffer;
    static ofWords(words: number[]): DynamicSmartBuffer;
    static ofUTF8String(str: string): DynamicSmartBuffer;
    toHexString(): string;
    toBinaryString(): string;
    toBase64String(): string;
    toWordsArray(): number[];
    toUTF8String(): string;
    private willWrite;
    writeUint8(val: number): void;
    writeUint16(val: number): void;
    writeUint32(val: number): void;
    writeBytes(val: Uint8Array): void;
    writeBuffer(val: SmartBuffer | DynamicSmartBuffer): void;
    writeBytes8Length(val: Uint8Array): void;
    writeBuffer8Length(val: SmartBuffer | DynamicSmartBuffer): void;
    writeString8Length(val: string): void;
    writeBytes16Length(val: Uint8Array): void;
    writeBuffer16Length(val: SmartBuffer | DynamicSmartBuffer): void;
    writeString16Length(val: string): void;
    writeBytes32Length(val: Uint8Array): void;
    writeBuffer32Length(val: SmartBuffer | DynamicSmartBuffer): void;
    writeString32Length(val: string): void;
    readUint8(): number;
    readUint16(): number;
    readUint32(): number;
    readBytes(length: number): Uint8Array;
    readBuffer(length: number): SmartBuffer;
    readDynamicBuffer(length: number): DynamicSmartBuffer;
    readBytes8Length(): Uint8Array;
    readBuffer8Length(): SmartBuffer;
    readString8Length(): string;
    readBytes16Length(): Uint8Array;
    readBuffer16Length(): SmartBuffer;
    readString16Length(): string;
    readBytes32Length(): Uint8Array;
    readBuffer32Length(): SmartBuffer;
    readString32Length(): string;
    get bytes(): Uint8Array;
}
